[package]
name = "smdhtool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bmp = "0.5.0"
clap = { version = "4.4.8", features = ["derive"] }
cytryna = { path = "../cytryna" }
