[package]
name = "cytryna"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.3"
bitflags = "2.4.1"
cbc = { version = "0.1.2", features = ["alloc"] }
ctr = { version = "0.9.2", features = ["std"] }
derivative = "2.2.0"
embedded-graphics = { version = "0.8.1", optional = true }
hex = "0.4.3"
memoffset = "0.9.0"
modular-bitfield = "0.11.2"
sha2 = "0.10.8"
static_assertions = "1.1.0"
thiserror = "1.0.50"

[features]
default = ["embedded_graphics"]
embedded_graphics = ["dep:embedded-graphics"]
